### ISSUE TITLE
Travis fails on py3.6 only

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium-apy#142]
See https://travis-ci.org/apertium/apertium-apy/builds/629740653 

```
======================================================================

FAIL: test_analyze (tests.test.TestAnalyzeHandler)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/tornado/testing.py", line 120, in __call__

    result = self.orig_method(*args, **kwargs)

  File "/home/travis/build/apertium/apertium-apy/tests/test.py", line 319, in test_analyze

    self.assertEqual(response, [['ikkje/ikkje<adv>', 'ikkje']])

AssertionError: Lists differ: [] != [['ikkje/ikkje<adv>', 'ikkje']]

Second list contains 1 additional elements.

First extra element 0:

['ikkje/ikkje<adv>', 'ikkje']

- []

+ [['ikkje/ikkje<adv>', 'ikkje']]

======================================================================

FAIL: test_coverage (tests.test.TestCoverageHandler)

----------------------------------------------------------------------

[W 191226 18:44:43 apy:70] Caught signal: 15

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/tornado/testing.py", line 120, in __call__

    result = self.orig_method(*args, **kwargs)

  File "/home/travis/build/apertium/apertium-apy/tests/test.py", line 396, in test_coverage

    self.assertListEqual(response, [0.5])

AssertionError: Lists differ: [1.0] != [0.5]

First differing element 0:

1.0

0.5

- [1.0]

+ [0.5]

======================================================================

FAIL: test_identify_lang (tests.test.TestIdentifyLangHandler)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/tornado/testing.py", line 120, in __call__

    result = self.orig_method(*args, **kwargs)

  File "/home/travis/build/apertium/apertium-apy/tests/test.py", line 390, in test_identify_lang

    self.assertAlmostEqual(response['nno'], 1.0)

AssertionError: -1 != 1.0 within 7 places

----------------------------------------------------------------------

Ran 32 tests in 3.447s

FAILED (failures=3, skipped=1)
```

I don't understand why this just happens with 3.6

**Comment by sushain97** [comment]
Wow spooky since Py3.6 is backwards compatible? Maybe we were depending on something like dictionary ordering? Pretty curious.

**Comment by ayushjainrksh** [comment]
I faced this bug last year. I reported the same but didn't create an issue back then as I felt the build was supposed to fail for Py3.6. Anyways I'll have a look at it.
